# Generated by Django 2.2.2 on 2019-06-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Course Name')),
                ('Course', models.CharField(max_length=2)),
                ('Course Percentage', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
