# Generated by Django 2.2.2 on 2019-06-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Course',
            new_name='course_grade',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Course Percentage',
            new_name='course_pct',
        ),
        migrations.AddField(
            model_name='course',
            name='course_semester',
            field=models.CharField(default='Chicken', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_year',
            field=models.IntegerField(default=1111),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
