# Generated by Django 2.2.2 on 2019-06-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0002_auto_20190605_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_pct',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Course Percentage'),
        ),
    ]
