# Generated by Django 2.2.2 on 2019-06-06 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0003_auto_20190605_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_credit_hours',
            field=models.IntegerField(default=0, verbose_name='Course Credit Hours'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='course_grade',
            field=models.CharField(max_length=2, verbose_name='Course Grade'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_semester',
            field=models.CharField(max_length=15, verbose_name='Course Semester'),
        ),
    ]
