# Generated by Django 2.2.2 on 2019-06-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0004_auto_20190606_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_grade_points',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Course Grade Points'),
            preserve_default=False,
        ),
    ]
